### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by dillfrescott** [mgdelacroix/mattermost-grumble-plugin#5]
Just wondering because this seems like a great plugin.

**Comment by jreoka** [comment]
I don't think it is active anymore :(

**Comment by mgdelacroix** [comment]
Apologies for the late response. The plugin is not active anymore, but if you want to have voice calls within Mattermost, I'd suggest to take a look at the Calls plugin: https://github.com/mattermost/mattermost-plugin-calls

**Comment by jreoka** [comment]
Oh, ok dont worry! Thank you for the info!
